name: Deployment Testing
on:
  pull_request:
  push:
    branches: [ deployment-testing ]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  builds:
    timeout-minutes: 90
    environment: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb  | sudo bash
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Check Azure
        run: |
          az account show
          az group list -o table
          ssh-keygen -t ecdsa -N "" -f tempssh
          delete_after="$(date --utc -d "+24 hours" +%F-%T)"
          vm_name="test-foovm"
          rg="rg-azure-nvme-utils-github-testing"
          az vm create --image Ubuntu2204 --ssh-key-values @tempssh.pub --admin-username testuser -g "$rg" -l eastus2euap -n "$vm_name" --tags "deleteAfter=$deleteAfter" --os-disk-delete-option Delete --nic-delete-option Delete
          az vm delete -n "$vm_name"
